# book settings
title: Using LLMs for recreating published DES models in simpy: feasibility and pilot
author: Thomas Monks
email: t.m.w.monks@exeter.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  sing LLMs for recreating published DES models in simpy: feasibility and pilot
# logo: content/imgs/small_logo.png

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: 'cache' #cache output from .ipynb files for faster build
  timeout: -1 #no time restriction on notebook execution
  
repository:
  url: https://github.com/pythonhealthdatascience/llm_simpy
  branch: main
  
html:
  use_repository_button: true
  use_issues_button: true
  
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url: "https://mybinder.org"
  #colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  thebe: true
