name: gen_simpy
channels:
  - conda-forge
dependencies:
  - joblib=1.2.0
  - jupyterlab=4.0.8
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.1
  - numpy=1.26.0
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.10.13
  - simpy=4.1.1
  - scipy=1.11.3